# =============================================================================
# Secrets que populam os envFrom: secretRef *-sqs (optional: true) das APIs.
# No overlay LOCAL, apontam pro Service "localstack" do cluster.
# =============================================================================
apiVersion: v1
kind: Secret
metadata:
  name: users-api-sqs
  namespace: fcg
type: Opaque
stringData:
  AWS__SQS__UserCreatedQueueUrl: "http://localstack:4566/000000000000/fcg-local-user-created-events"
  AWS_ACCESS_KEY_ID: "test"
  AWS_SECRET_ACCESS_KEY: "test"
  AWS_DEFAULT_REGION: "us-east-1"
  AWS_ENDPOINT_URL: "http://localstack:4566"
  AWS_ENDPOINT_URL_SQS: "http://localstack:4566"
---
apiVersion: v1
kind: Secret
metadata:
  name: payments-api-sqs
  namespace: fcg
type: Opaque
stringData:
  AWS__SQS__PaymentProcessedQueueUrl: "http://localstack:4566/000000000000/fcg-local-payment-processed-events"
  AWS_ACCESS_KEY_ID: "test"
  AWS_SECRET_ACCESS_KEY: "test"
  AWS_DEFAULT_REGION: "us-east-1"
  AWS_ENDPOINT_URL: "http://localstack:4566"
  AWS_ENDPOINT_URL_SQS: "http://localstack:4566"
