apiVersion: v1
kind: ConfigMap
metadata:
  name: catalog-api-config
  namespace: fcg
data:
  ASPNETCORE_ENVIRONMENT: "Production"
  Jwt__Issuer: "FiapCloudGames"
  Jwt__Audience: "FiapCloudGames"
  RabbitMQ__Host: "rabbitmq"
  RabbitMQ__Username: "guest"
---
apiVersion: v1
kind: Secret
metadata:
  name: catalog-api-secret
  namespace: fcg
type: Opaque
stringData:
  ConnectionStrings__Catalog: "Host=postgres;Port=5432;Database=catalog_db;Username=postgres;Password=postgres"
  Jwt__Key: "change-this-secret-key-min-32-chars!!"
  RabbitMQ__Password: "guest"
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: catalog-api
  namespace: fcg
spec:
  replicas: 1
  selector:
    matchLabels:
      app: catalog-api
  template:
    metadata:
      labels:
        app: catalog-api
    spec:
      containers:
        - name: catalog-api
          image: catalog-api:latest
          imagePullPolicy: Never
          ports:
            - containerPort: 8080
          envFrom:
            - configMapRef:
                name: catalog-api-config
            - secretRef:
                name: catalog-api-secret
---
apiVersion: v1
kind: Service
metadata:
  name: catalog-api
  namespace: fcg
spec:
  selector:
    app: catalog-api
  ports:
    - port: 80
      targetPort: 8080
  type: ClusterIP
