apiVersion: v1
kind: ConfigMap
metadata:
  name: users-api-config
  namespace: fcg
data:
  ASPNETCORE_ENVIRONMENT: "Production"
  Jwt__Issuer: "FiapCloudGames"
  Jwt__Audience: "FiapCloudGames"
  RabbitMQ__Host: "rabbitmq"
  RabbitMQ__Username: "guest"
---
apiVersion: v1
kind: Secret
metadata:
  name: users-api-secret
  namespace: fcg
type: Opaque
stringData:
  ConnectionStrings__Users: "Host=postgres;Port=5432;Database=users_db;Username=postgres;Password=Pg$Fgc2026!K9mN3bR7xQ"
  Jwt__Key: "Jwt$Fgc2026!Xp7mK3nQ9wL5vR2tJ8bD4N"
  RabbitMQ__Password: "Rmq$Fgc2026!Q5bT8xM6Y"
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: users-api
  namespace: fcg
spec:
  replicas: 1
  selector:
    matchLabels:
      app: users-api
  template:
    metadata:
      labels:
        app: users-api
    spec:
      initContainers:
        - name: wait-for-postgres
          image: busybox:1.36
          command: ['sh', '-c', 'until nc -z postgres 5432; do echo waiting for postgres; sleep 2; done']
        - name: wait-for-rabbitmq
          image: busybox:1.36
          command: ['sh', '-c', 'until nc -z rabbitmq 5672; do echo waiting for rabbitmq; sleep 2; done']
      containers:
        - name: users-api
          image: users-api:latest
          imagePullPolicy: Never
          ports:
            - containerPort: 8080
          envFrom:
            - configMapRef:
                name: users-api-config
            - secretRef:
                name: users-api-secret
---
apiVersion: v1
kind: Service
metadata:
  name: users-api
  namespace: fcg
spec:
  selector:
    app: users-api
  ports:
    - port: 80
      targetPort: 8080
  type: ClusterIP
