apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: users-postgres-pvc
  namespace: fcg
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: users-postgres
  namespace: fcg
spec:
  replicas: 1
  selector:
    matchLabels:
      app: users-postgres
  template:
    metadata:
      labels:
        app: users-postgres
    spec:
      automountServiceAccountToken: false
      securityContext:
        runAsUser: 70
        runAsGroup: 70
        fsGroup: 70
        seccompProfile:
          type: RuntimeDefault
      containers:
        - name: users-postgres
          image: postgres:16-alpine
          ports:
            - containerPort: 5432
          securityContext:
            allowPrivilegeEscalation: false
            capabilities:
              drop: ["ALL"]
              add: ["CHOWN", "FOWNER", "SETUID", "SETGID"]
          resources:
            requests:
              memory: "128Mi"
              cpu: "100m"
            limits:
              memory: "512Mi"
              cpu: "500m"
          env:
            - name: POSTGRES_USER
              value: "postgres"
            - name: POSTGRES_PASSWORD
              value: "Pg$Fgc2026!K9mN3bR7xQ"
            - name: POSTGRES_DB
              value: "users_db"
          readinessProbe:
            exec:
              command: ["pg_isready", "-U", "postgres"]
            initialDelaySeconds: 5
            periodSeconds: 5
            failureThreshold: 10
          volumeMounts:
            - mountPath: /var/lib/postgresql/data
              name: users-postgres-storage
      volumes:
        - name: users-postgres-storage
          persistentVolumeClaim:
            claimName: users-postgres-pvc
---
apiVersion: v1
kind: Service
metadata:
  name: users-postgres
  namespace: fcg
spec:
  selector:
    app: users-postgres
  ports:
    - port: 5432
      targetPort: 5432
  type: ClusterIP
