apiVersion: v1
kind: Secret
metadata:
  name: catalog-api-secret
  namespace: fcg
type: Opaque
stringData:
  ConnectionStrings__Catalog: "Host=catalog-postgres;Port=5432;Database=catalog_db;Username=postgres;Password=g0UxLYGSgPdLM6Fy2ma37Tvdqp8RPg#"
  Jwt__RsaPublicKey: "LS0tLS1CRUdJTiBQVUJMSUMgS0VZLS0tLS0KTUlJQklqQU5CZ2txaGtpRzl3MEJBUUVGQUFPQ0FROEFNSUlCQ2dLQ0FRRUFrTE1rR3habHJMZmRvQUtlMVVWbQozK0ZXbDdxOHVGVTJ4MXhSQlA5RVQ2WTRMa3RYempwanFodldjU3E2NVRiZ2c5S3QxK1FDdGErUGVaL2p1eDNMClVZeENNVS85Rk5raGRaTXJUR1hxczQzc0c4bGk5cVd5L0g2RUhEeHVzWTZiT0xPbGxPRTVlaWhLcFk2ZXNacG0KN1lhNkt3R212Z2l1NGxyRkRhRUNSRU5BdGlyMEtoTU1DV1JHK0hLNy8rbFA2NkxGc0Z0OXowRGhpVzlhL1p5QQp3RnRta1I3SFJYbTFJMDFoTzJZaDlpYllTSGF3K0VydFNTcVhUQWxWNHY2NFl0OG9JN1BBdGhyWXJIc050L1VkCklKSzdDclVOWUdRMHU5V2F0VlRueWxsZmk5aDNRdTNBazRyQzF6VE43eTB1bE55WVhsZnM0S2dlUVg4L1NSbmoKOXdJREFRQUIKLS0tLS1FTkQgUFVCTElDIEtFWS0tLS0tCg=="
  RabbitMQ__Password: "Eme96qBU9T4enJk9WONhrERmq!"
  Redis__ConnectionString: "redis:6379,password=5k1MJXOzE19Z0oYiFd91jYRds!"
